packaging: fix build on openSUSE Leap 16.0
Due to an upstream change, python3 must now be explicitly installed in
the Dockerfile for openSUSE Leap 16.0, otherwise packaging fails:

  error: Failed build dependencies:
          python3 is needed by jami-20260807.0-1.x86_64

Change-Id: I0ff388ece41cfc9e4a4f3af93f82fafdc10ed527