Update patch set 19
Patch Set 19:

Also

+ '[' true = true ']'
+ '[' '' ']'
+ cmake .. -DQT5_VER= -DQT5_PATH= -DCMAKE_PREFIX_PATH=
CMake Warning (dev) at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:273 (message):
  The package name passed to `find_package_handle_standard_args`
  (LIB_RING_CLIENT) does not match the name of the calling package
  (LibRingClient).  This can lead to problems in calling code that expects
  `find_package` result variables (e.g., `_FOUND`) to follow a certain
  pattern.
Call Stack (most recent call first):
  /usr/local/lib/cmake/LibRingClient/LibRingClientConfig.cmake:63 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:188 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

Will expect lrc headers in /usr/local/include/libringclient
Releasing and copying translation files
-- Configuring done
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
Xss
    linked by target "jami-qt" in directory /home/amarok/Projects/jami/client-qt

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
Traceback (most recent call last):
  File "/home/amarok/Projects/jami/./make-ring.py", line 651, in <module>
    main()
  File "/home/amarok/Projects/jami/./make-ring.py", line 638, in main
    run_install(parsed_args)
  File "/home/amarok/Projects/jami/./make-ring.py", line 397, in run_install
    return subprocess.run(["./scripts/install.sh"] + install_args, env=environ, check=True)
  File "/usr/lib64/python3.9/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['./scripts/install.sh', '-p', '4', '-g', '-c', 'client-qt', '-q', '5.15.0', '-Q', '']' returned non-zero exit status 1.

Patch-set: 19
Reviewer: Gerrit User 220 <220@1e26b4c1-6b8c-47ff-9df7-501b633d3b5a>