tests: fix building of previewengine_unittest
This test started failing to build with Qt 6.8.2 and/or GCC 14 in
Guix:

   error: ‘class QHttpServer’ has no member named ‘listen’
      31 |         server->listen(QHostAddress::LocalHost, 8000);

Adjust to use what the Qt documentation suggests, which is to bind the
server to a distinct QTcpServer instance.

Fixes: #1144
Change-Id: I3308acab793b3cdf74458f8196933bca26b41bb1