libclient: Explicitly link to avutil when using libwrap.
Otherwise, when libjami is compiled as a shared library and
dynamically linked with all its dependencies (including ffmpeg), the
build would fail with:

  ld: src/libclient/liblibjamiclient.a(directrenderer.cpp.o):
  undefined reference to symbol 'av_frame_alloc@@LIBAVUTIL_56'
  ld: /gnu/store/...-ffmpeg-jami-4.4.2/lib/libavutil.so.56:
  error adding symbols: DSO missing from command line

* src/libclient/CMakeLists.txt: Call find_library for avutil, with
hints for contrib path on GNU/Linux and macOS.
[ENABLE_LIBWRAP]: Add target link to avutil if not on Windows.

Co-authored-by: Kateryna Kostiuk <kateryna.kostiuk@savoirfairelinux.com>
Co-authored-by: Amin Bandali <amin.bandali@savoirfairelinux.com>
Change-Id: Id9681132b046fd828002cd3daa24afc8a6dd1eae